
namespace KangShuoTech.DataAccessProjects.Model
{
    public class BTypeModel
    {             
        public int ID { get; set; }        
        public int RECID { get; set; }         
        public string PTNNM { get; set; }        
        public string PTNSEX { get; set; }
        public int PTNAGE { get; set; }
        public string CHKNO { get; set; }
        public string APPOFF { get; set; }
        public string CHKPART { get; set; }
        public string PRETM { get; set; }
        public string DIAGTM { get; set; }
        public string PRNTM { get; set; }
        public string PICTIME { get; set; }
        public string INHSPTM { get; set; }
        public string OUTHSPTM { get; set; }
        public string FST2ND { get; set; }        
        public string CHKMODE { get; set; }
        public string SMPPART { get; set; }
        public string SMPTISS { get; set; }
        public string APPDR { get; set; }
        public string DIAGDR { get; set; }
        public string CLNCDIAG { get; set; }
        public string CHKVIEW { get; set; }     
        public string DIAG { get; set; }
        public string PREOPDIAG { get; set; }
        public string POSTOPDIAG { get; set; }
        public string PATHOVIEW { get; set; }
        public string PATHODIAG { get; set; }
        public string INHSPDIAG { get; set; }
        public string OUTHSPDIAG { get; set; }
        public string BIOCHM { get; set; }
        public string BLOOD { get; set; }
        public string NURO { get; set; }
        public string PTNTELL { get; set; }
        public string CHKITEM { get; set; }
        public string PTNHIS { get; set; }
        public string FMLYHIS { get; set; }
        public string CURHIS { get; set; }
        public string GUOMHIS { get; set; }
        public string FRZHIS { get; set; }
        public string LASERHIS { get; set; }
        public string DRUG { get; set; }
        public string PREDRUG { get; set; }
        public string PTNIDNO { get; set; }
        public string MARRIED { get; set; }
        public string PTNTEL { get; set; }
        public string POSTCD { get; set; }
        public string PTNADDR { get; set; }
        public string PTNOFF { get; set; }
        public string PTNOCCU { get; set; }
        public string DYS { get; set; }
        public string NODYS { get; set; }        
        public string DYS1 { get; set; }
        public string DYS2 { get; set; }
        public string DYS3 { get; set; }
        public string DYS4 { get; set; }
        public string PIS1 { get; set; }
        public string PIS2 { get; set; }
        public string PIS3 { get; set; }
        public string PIS4 { get; set; }
        public string PRESTS { get; set; }
        public string CHKSTS { get; set; }
        public string PRNSTS { get; set; }
        public string SAVESTS { get; set; }
        public string CHGHSP { get; set; }
        public string CHGDR { get; set; }
        public string DOCNO { get; set; }
        public string AREANO { get; set; }
        public string BEDNO { get; set; }
        public string HSPNO { get; set; }
        public string MENZHENNO { get; set; }
        public string PATHONO { get; set; }
        public string PISNO { get; set; }
        public string BUSNO { get; set; }
        public string CTNO { get; set; }
        public string XNO { get; set; }
        public string ECGNO { get; set; }
        public string TEAMNO { get; set; }
        public string DRTELLNO { get; set; }
        public string PICNO { get; set; }
        public string PTNTYPE { get; set; }
        public string CHKFEE { get; set; }
        public int DIAGFEE { get; set; }
        public string DRUGFEE { get; set; }
        public string GUAHAOFEE { get; set; }
        public string CUREFEE { get; set; }
        public string TTLFEE { get; set; }
        public string PUBFEE { get; set; }
        public string PRVFEE { get; set; }
        public string SECUFEE { get; set; }
        public string ILLPRD { get; set; }
        public string ILLSTS { get; set; }
        public string ILLCMP { get; set; }
        public string ILLRSN { get; set; }
        public string IMPRESS { get; set; }
        public string CHKAIM { get; set; }
        public string PREDIAG { get; set; }
        public string PROC { get; set; }
        public string MAZUI { get; set; }
        public string PLANNING { get; set; }
        public string ADVICE { get; set; }
        public string VISIT { get; set; }
        public string EFFECT { get; set; }
        public string SATIS { get; set; }
        public string DEVICETYPE { get; set; }
        public string DEVICEMODEL { get; set; }
        public string DEVICENO { get; set; }
        public string WRKPATH { get; set; }
        public string CMPTER { get; set; }
        public string BZ1 { get; set; }
        public string BZ2 { get; set; }
        public string BZ3 { get; set; }
        public string BZ4 { get; set; }
        public string PICORDER { get; set; }
        public string PICTURN { get; set; }
        public string PICCONS1 { get; set; }
        public string PICCONS2 { get; set; }
        public string PICCONS3 { get; set; }
        public string PICCONS4 { get; set; }
        public string PICCONS5 { get; set; }
        public string PICCONS6 { get; set; }
        public string SCANPIES1 { get; set; }
        public string SCANTHICK1 { get; set; }
        public string SCANDIST1 { get; set; }
        public string SCANLN1 { get; set; }
        public string SCANPIES2 { get; set; }
        public string SCANTHICK2 { get; set; }
        public string SCANDIST2 { get; set; }
        public string SCANLN2 { get; set; }
        public string SCANPIES3 { get; set; }
        public string SCANTHICK3 { get; set; }
        public string SCANDIST3 { get; set; }
        public string SCANLN3 { get; set; }
        public string SCANPIES4 { get; set; }
        public string SCANTHICK4 { get; set; }
        public string SCANDIST4 { get; set; }
        public string SCANLN4 { get; set; }
        public string JINJ { get; set; }
        public string CD { get; set; }
        public string ZC { get; set; }        
        public string YZ { get; set; }
        public string JJ { get; set; }
        public string HJ { get; set; }
        public string SJ { get; set; }
        public string MC { get; set; }
        public string HM { get; set; }
        public string CX { get; set; }
        public string YS { get; set; }
        public string XZ { get; set; }
        public string JCX { get; set; }
        public string BX { get; set; }
        public string TT { get; set; }
        public string FM { get; set; }
        public string TC { get; set; }
        public string HN { get; set; }
        public string BR { get; set; }
        public string BC { get; set; }
        public string GLV { get; set; }
        public string KN { get; set; }
        public string SY { get; set; }
        public string GQ { get; set; }
        public string PQ { get; set; }
        public string XIBS { get; set; }
        public string SG { get; set; }
        public string BM { get; set; }
        public string WD { get; set; }
        public string WT { get; set; }
        public string WJ { get; set; }
        public string WDO { get; set; }
        public string YM { get; set; }
        public string SEZ { get; set; }
        public string HP { get; set; }
        public string TZ { get; set; }
        public string YY { get; set; }
        public string SS { get; set; }
        public string SZ { get; set; }
        public string ST { get; set; }
        public string QT { get; set; }
        public string XF { get; set; }
        public string FB { get; set; }
        public string XY { get; set; }
        public string QW { get; set; }
        public string GP { get; set; }
        public string M { get; set; }
        public string S { get; set; }
        public string WZ { get; set; }
        public string NZ { get; set; }
        public string GL { get; set; }
        public string Z1DX { get; set; }
        public string Z2DX { get; set; }
        public string Z3DX { get; set; }
        public string Z4DX { get; set; }
        public string Z1S { get; set; }
        public string Z2S { get; set; }
        public string Z3S { get; set; }
        public string Z4S { get; set; }
        public string Z1N { get; set; }
        public string Z2N { get; set; }
        public string Z3N { get; set; }
        public string Z4N { get; set; }
        public string QT1 { get; set; }
    }
}
