namespace KangShuoTech.CommomDataAccessProjects.CommonModel
{
    using System;

    [Serializable]
    public class RecordsBaseInfoModel
    {
        public RecordsBaseInfoModel() { }

        public string RecordID { get; set; }
        public string IDCardNo { get; set; }
        public string CustomerID { get; set; }
        public decimal? OrgProvinceID { get; set; }
        public decimal? OrgCityID { get; set; }
        public decimal? OrgDistrictID { get; set; }
        public decimal? OrgTownID { get; set; }
        public decimal? OrgVillageID { get; set; }
        public decimal? ProvinceID { get; set; }
        public decimal? CityID { get; set; }
        public decimal? TownID { get; set; }
        public decimal? VillageID { get; set; }
        public string WorkUnit { get; set; }
        public string LiveType { get; set; }
        public string Nation { get; set; }
        public string Minority { get; set; }
        public string RH { get; set; }
        public string Culture { get; set; }
        public string Job { get; set; }
        public string MaritalStatus { get; set; }
        public string MedicalPayType { get; set; }
        public string MedicalPayTypeOther { get; set; }
        public string DrugAllergic { get; set; }
        public string DrugAllergicOther { get; set; }
        public string Disease { get; set; }
        public string DiseaseEx { get; set; }
        public string DiseasEndition { get; set; }
        public string DiseasEnditionEx { get; set; }
        public string CustomerName { get; set; }
        public string Doctor { get; set; }
        public string Sex { get; set; }
        public DateTime? Birthday { get; set; }
        public string ContactName { get; set; }
        public string ContactPhone { get; set; }
        public string BloodType { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string HouseHoldAddress { get; set; }
        public decimal? CreateUnit { get; set; }
        public string Exposure { get; set; }
        public string PopulationType { get; set; }
        public string FamilyIDCardNo { get; set; }
        public string HouseRelation { get; set; }
        public string HouseRealOther { get; set; }
        public string Email { get; set; }
        public string TownName { get; set; }
        public string VillageName { get; set; }
        public string CreateUnitName { get; set; }
        public string CreateMenName { get; set; }
        public string CreateBy { get; set; }
        public DateTime? CreateDate { get; set; }
        public string LastUpdateBy { get; set; }
        public DateTime? LastUpdateDate { get; set; }
        public string IsUpdate { get; set; }
        public string IsDelete { get; set; }
        public decimal? DistrictID { get; set; }
        public string HouseID { get; set; }
        public string HouseName { get; set; }
        public int ID { get; set; }
        public decimal? age { get; set; }
        public string KidFlage { get; set; }// ¶ùÍ¯µÇÂ¼

        //ÐÂÔö×Ö¶Î
        public string OrgName { get; set; }
        public decimal? FamilyNum { get; set; }
        public string FamilyStructure { get; set; }
        public string TownMedicalCard { get; set; }
        public string ResidentMedicalCard { get; set; }
        public string PovertyReliefMedicalCard { get; set; }
        public string LiveCondition { get; set; }
        public string PreSituation { get; set; }
        public string PreNum { get; set; }
        public string YieldNum { get; set; }
        public string Chemical { get; set; }
        public string Poison { get; set; }
        public string Radial { get; set; }
        public string AddressNo { get; set; }
        public string HouseHoldAddressNo { get; set; }
        public string IsPoorfy { get; set; }
        public string PoorPeople { get; set; }
        public string HomePhone { get; set; }
        public string FloatingPeople { get; set; }
        public string IDAddress { get; set; }
        public string FamilyAddress { get; set; }
        public string FamilyDeAddress { get; set; }
        public string Grid { get; set; }
        public string HouseHoldDeAddress { get; set; }
        public string BornAddress { get; set; }
        public string NativePlace { get; set; }
        public string DeAddress { get; set; }
        public DateTime? AddressDate { get; set; }
        public string AddressMonth { get; set; }
        public string ResideType { get; set; }
        public DateTime? ManageDate { get; set; }
        public string FlowType { get; set; }
        public string LandlordName { get; set; }
        public string FlowOrg { get; set; }
        public string FlowReason { get; set; }
        public DateTime? ImmigrateDate { get; set; }
        public string MaternalHealth { get; set; }
        public string FlowOther { get; set; }
        public string OtherCerType { get; set; }
        public string OtherCerNo { get; set; }
        public string PersonState { get; set; }
        public string CitizenNo { get; set; }
        public string HealthNo { get; set; }
        public string NcmsNo { get; set; }
        public string MedicalNo { get; set; }
        public string VisitNo { get; set; }
        public string KidCareNo { get; set; }
        public string BrithNo { get; set; }
        public string SpeciesNo { get; set; }
        public string IsSign { get; set; }
        public string Remark { get; set; }
        public string ResideProperty { get; set; }
        public decimal? ChildrenNum { get; set; }
        public string Guardian1 { get; set; }
        public string GuardianRelation1 { get; set; }
        public string GuardianPhone1 { get; set; }
        public string Guardian2 { get; set; }
        public string GuardianRelation2 { get; set; }
        public string GuardianPhone2 { get; set; }
        public DateTime? DrugAllergicDate { get; set; }
        public string DrugAllergicRemark { get; set; }
        public string DisabilityNo { get; set; }
        public string DisabilityLevel { get; set; }
        public DateTime? SignDate { get; set; }
        public string SingDoctor { get; set; }
        public string Parents { get; set; }
        public string InoculateNo { get; set; }
        public decimal? Parity { get; set; }
        public decimal? Production { get; set; }
        public decimal? HumanFolwNo { get; set; }
        public decimal? OdinopoeiaNo { get; set; }
        public string Contraceptive { get; set; }
        public decimal? MenarcheAge { get; set; }
        public decimal? MenopauseAge { get; set; }
        public decimal? MenstrualCycle { get; set; }
        public decimal? MenstrualDays { get; set; }
        public string MenstrualVolume { get; set; }
        public string MenstrualOther { get; set; }
        public string FlowReg { get; set; }
        public string PhysicalClass { get; set; }
        public string SocialRelations { get; set; }
        public string UploadID { get; set; }
        public string MedicalInsuranceFlag { get; set; }
        public string SignFlag { get; set; }
        public string PostalCode { get; set; }
        public string BankNo { get; set; }
        public string MedicalCerNo { get; set; }
        public string MedicalCardNo { get; set; }
        public string HealthCardNo { get; set; }
        public string VaccinationNo { get; set; }
        public string GuardianRalation1 { get; set; }
        public string GuardianRalation2 { get; set; }
        public string DisableFlag { get; set; }
        public string DisableNo { get; set; }
        public string GuarantFlag { get; set; }
        public string GuarantNo { get; set; }
        public string SubsistenceFlag { get; set; }
        public string SubsistenceNo { get; set; }
        public string PoorFlag { get; set; }
        public string PoorNo { get; set; }
        public string LowIncomeFlag { get; set; }
        public string IssueFlag { get; set; }
        public string SMSFlag { get; set; }
        public string DoctorPhone { get; set; }
        public string UserName { get; set; }
        public string UserPas { get; set; }
        public string PrivacyLevel { get; set; }
        public string TransferFlag { get; set; }
        public DateTime? TransferDate { get; set; }
        public string TransferReason { get; set; }
        public string SystemNo { get; set; }
        public DateTime? ManageTiem { get; set; }
        public DateTime? PenicilinTime { get; set; }
        public string PenicilinRemark { get; set; }
        public DateTime? SulfaTime { get; set; }
        public string SulfaRemark { get; set; }
        public DateTime? SteptomycinTime { get; set; }
        public string SteptomycinRemark { get; set; }
        public DateTime? DrugOtherTime { get; set; }
        public string DrugOtherRemark { get; set; }
        public string State { get; set; }
        public string CardNo { get; set; }
        public string Postcode { get; set; }
        public string DataSource { get; set; }
        public string Country { get; set; }
        public string CityType { get; set; }
        public string ResidenceType { get; set; }
        public DateTime? LiveDate { get; set; }
        public string SocialCard { get; set; }
        public string PayCard { get; set; }
        public string DisableCard { get; set; }
        public string CertificateType { get; set; }
        public string CertificateNo { get; set; }
        public string LowerFlag { get; set; }
        public string LowerCard { get; set; }
        public string ManageUnite { get; set; }
        public string ExamineFlag { get; set; }
        public DateTime? ExamineDate { get; set; }
        public string Auditor { get; set; }
        public string EndReason { get; set; }
        public string EndFlag { get; set; }
        public DateTime? EndDate { get; set; }
        public string DeathFlag { get; set; }
        public DateTime? DeathDate { get; set; }
        public string DeathReason { get; set; }
        public string SingnFlag { get; set; }
        public DateTime? SingnDate { get; set; }
        public string SingnDoctor { get; set; }
        public string FileSource { get; set; }
        public string PaperKeeper { get; set; }
        public string Remarks { get; set; }
        public string Groups { get; set; }
        public string SpecialCrowd { get; set; }
        public string MobileNumber { get; set; }
        public string FamilyDoctorSign { get; set; }
        public string NowAddrDoorNo { get; set; }
        public string AddrDoorNo { get; set; }
        public string InPerson { get; set; }
        public string Contract { get; set; }
        public string Investigators { get; set; }
        public DateTime? InvestigatorsTime { get; set; }
        public string CheckOut { get; set; }
        public string Death { get; set; }
        public DateTime? DeathTime { get; set; }
        public DateTime? CheckOutTime { get; set; }
        public string Inputer { get; set; }
        public string LastUpdateMan { get; set; }
        public string DistrictName { get; set; }
        public decimal? ZuID { get; set; }
        public string isProfile { get; set; }
        public string FamilyRegister { get; set; }
    }
}